version: '3.7'

services:
  django-web:
    build: .
    container_name: wifi-counter
    expose:
      - 8000
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    env_file:
      - .env
    volumes:
      - django_data:/app/data
      - django_static:/app/staticfiles

  nginx:
    image: nginx:latest
    container_name: wifi-counter-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/app/staticfiles


volumes:
  django_data:
  django_static: