version: '3.7'

services:
  django-web:
    build: .
    container_name: wifi-counter
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
    env_file:
      - .env
    volumes:
      django_data:/app/data

volumes:
  django_data: