version: '3.7'

services:
  django-web:
    build: .
    container_name: wifi-counter
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    env_file:
      - .env
    volumes:
      django_data:/app/data

volumes:
  django_data: